



apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer
  labels:
    run: blockchain-orderer
spec:
  type: ClusterIP
  selector:
    name: orderer
  ports:
    - protocol: TCP
      port: 31010
      name: grpc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-orderer
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: orderer
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:amd64-
          command: ["sh", "-c", "orderer"]
          env:
            - name: TZ
              value: 
            - name: ORDERER_CFG_PATH
              value: /fabric/
            - name: ORDERER_GENERAL_LEDGERTYPE
              value: file
            - name: ORDERER_FILELEDGER_LOCATION
              value: /fabric/ledger/orderer
            - name: ORDERER_GENERAL_BATCHTIMEOUT
              value: 1s
            - name: ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT
              value: "10"
            - name: ORDERER_GENERAL_MAXWINDOWSIZE
              value: "1000"
            - name: CONFIGTX_GENERAL_ORDERERTYPE
              value: kafka
            - name: CONFIGTX_ORDERER_KAFKA_BROKERS
              value: ""
            - name: ORDERER_KAFKA_RETRY_SHORTINTERVAL
              value: 1s
            - name: ORDERER_KAFKA_RETRY_SHORTTOTAL
              value: 30s
            - name: ORDERER_KAFKA_VERBOSE
              value: "true"
            - name: CONFIGTX_ORDERER_ADDRESSES
              value: ""
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: 
            - name: ORDERER_GENERAL_LISTENPORT
              value: ""
            - name: ORDERER_GENERAL_LOGLEVEL
              value: >
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /fabric/crypto-config/ordererOrganizations/.com/orderers/orderer..com/msp
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_GENESISFILE
              value: /fabric/genesis.block
            - name: ORDERER_GENERAL_GENESISPROFILE
              value: initial
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "false"
            - name: GODEBUG
              value: "netdns=go"
            - name: ORDERER_GENERAL_LEDGERTYPE
              value: "ram"
          volumeMounts:
            - mountPath: /fabric
              name: fabricfiles
