#!/usr/bin/env ruby

print '
    Created by Blockchain IT,
    If you need Fullstack, Blockchain or DevOps services
    contact us on info@blockchain-it.hr

    Happy hacking ;)
    Edi

'

require "yaml"
require "erb"

# generic variables
@config = YAML.load_file("environment.yaml")
@organizations = @config["organizations"]

#####################################################################
# Create config files for each node
#####################################################################



def set_node_template_vars(values)
  @version = values["version"]
  @organizations = values["organizations"]
  return
end

def set_general_config
  @version = @config["version"]
  @namespace = @config["namespace"]
  @hostname = @config["hostname"]
  @databaseHost = @config["databaseHost"]
  @databaseUsername = @config["databaseUsername"]
  @databasePassword = @config["databasePassword"]
  @databaseDatabase = @config["databaseDatabase"]
  return
end

def set_peer_template_vars(values)
  @name         = values["name"]
  @selector     = values["selector"]
  return
end

@organizations.each do |organization|
  @organizationName = organization.keys.first
  organization.values.first.each do |peer|
    @peerName = peer.keys.first
    set_peer_template_vars(peer.values.first)
  end
end

##Initialize
set_general_config


#####################################################################
# Claims
#####################################################################
File.open("yaml/claims.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/claims.yaml.erb"), nil, "-").result)
end

#####################################################################
# Fabric tools
#####################################################################
File.open("yaml/fabric-tools.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/fabric-tools.yaml.erb"), nil, "-").result)
end

#####################################################################
# Hyperledger Explorer 
#####################################################################
File.open("yaml/explorer.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/explorer.yaml.erb"), nil, "-").result)
end

#####################################################################
# Certificate Authority
#####################################################################
File.open("yaml/ca.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/ca.yaml.erb"), nil, "-").result)
end

#####################################################################
# Orderers 
#####################################################################
File.open("yaml/orderers.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/orderers.yaml.erb"), nil, "-").result)
end

#####################################################################
# Peers 
#####################################################################
File.open("yaml/peers.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/peers.yaml.erb"), nil, "-").result)
end

#####################################################################
# Deployment
#####################################################################
File.open("yaml/deployment.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/deployment.yaml.erb"), nil, "-").result)
end

