#!/usr/bin/env ruby

print '
    Created by Blockchain IT,
    If you need Fullstack, Blockchain or DevOps services
    contact us on info@blockchain-it.hr

    Happy hacking ;)
    Edi

'

require "yaml"
require "erb"

# generic variables
@config = YAML.load_file("environment.yaml")
@organizations = @config["organizations"]

#####################################################################
# Create config files for each node
#####################################################################

def set_node_template_vars(values)
  @version = values["version"]
  @organizations = values["organizations"]
  return
end

#####################################################################
# Claims
#####################################################################
File.open("yaml/claims.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/claims.yaml.erb"), nil, "-").result)
end

#####################################################################
# Fabric tools
#####################################################################
File.open("yaml/fabric-tools.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/fabric-tools.yaml.erb"), nil, "-").result)
end

#####################################################################
# Hyperledger Explorer 
#####################################################################
File.open("yaml/explorer.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/explorer.yaml.erb"), nil, "-").result)
end

#####################################################################
# Certificate Authority
#####################################################################
File.open("yaml/ca.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/ca.yaml.erb"), nil, "-").result)
end

#####################################################################
# Orderers 
#####################################################################
File.open("yaml/orderers.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/orderers.yaml.erb"), nil, "-").result)
end

#####################################################################
# Peers 
#####################################################################
File.open("yaml/peers.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/peers.yaml.erb"), nil, "-").result)
end


#####################################################################
# Deployment
#####################################################################
File.open("yaml/deployment.yaml", "w") do |f|
  f.puts (ERB.new(File.read("erb/deployment.yaml.erb"), nil, "-").result)
end

