#!/usr/bin/env ruby

require "yaml"
require "erb"

# generic variables
@config     = YAML.load_file("kuberneteth.yaml")
@nodes      = @config["nodes"]

#####################################################################
# Create config files for each node
#####################################################################

def set_node_template_vars(values)
  @version         = values["version"]
  return
end

#@nodes.each do |node|
#  set_node_template_vars(node.values.first)
#
#  File.open("#{@Node_UserIdent}.toml", "w") do |f|
#    f.puts (ERB.new(File.read("node.toml.erb"), nil, "-").result)
#  end
#end

#####################################################################
# Claims
#####################################################################
File.open("yaml/claims.yaml", "w") do |f|
  f.puts (ERB.new(File.read("yaml/claims.yaml.erb"), nil, "-").result)
end

#####################################################################
# Fabric tools
#####################################################################
File.open("yaml/fabric-tools.yaml", "w") do |f|
  f.puts (ERB.new(File.read("yaml/fabric-tools.yaml.erb"), nil, "-").result)
end

#####################################################################
# Hyperledger Explorer 
#####################################################################
File.open("yaml/explorer.yaml", "w") do |f|
  f.puts (ERB.new(File.read("yaml/explorer.yaml.erb"), nil, "-").result)
end

#####################################################################
# Orderers 
#####################################################################
File.open("yaml/orderers.yaml", "w") do |f|
  f.puts (ERB.new(File.read("yaml/orderers.yaml.erb"), nil, "-").result)
end

#####################################################################
# Peers 
#####################################################################
File.open("yaml/peers.yaml", "w") do |f|
  f.puts (ERB.new(File.read("yaml/peers.yaml.erb"), nil, "-").result)
end

#####################################################################
# Deployment
#####################################################################
File.open("yaml/deployment.yaml", "w") do |f|
  f.puts (ERB.new(File.read("yaml/deployment.yaml.erb"), nil, "-").result)
end

