apiVersion: v1
kind: Service
metadata:
  name: blockchain-org3peer1
  labels:
    run: blockchain-org3peer1
spec:
  type: ClusterIP 
  selector:
    name: org3peer1
  ports:
  - protocol: TCP
    port: 30110
    name: grpc
  - protocol: TCP
    port: 30111
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb
