OrdererOrgs:
  - Name: Orderer
    Domain: "{{ NAMESPACE }}.com"
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: '{{ORG1}}'
    Domain: "{{ORG1}}.{{NAMESPACE}}.com"
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
  - Name: '${ORG2}'
    Domain: '${ORG2}.${NAMESPACE}.com'
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
  - Name: '${ORG3}'
    Domain: '${ORG3}.${NAMESPACE}.com'
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2