# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

services:
  orderer.private.data.marketplace.com:
    container_name: orderer.private.data.marketplace.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
    #- FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LOGLEVEL=debug
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    # enabled TLS
    - ORDERER_GENERAL_TLS_ENABLED=false
    #- ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    #- ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    #- ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
    - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/private.data.marketplace.com/orderers/orderer.private.data.marketplace.com/msp/:/var/hyperledger/orderer/msp
    #- ./crypto-config/ordererOrganizations/private.data.marketplace.com/orderers/orderer.private.data.marketplace.com/tls/:/var/hyperledger/orderer/tls
    #- ./crypto-config/peerOrganizations/buyer.private.data.marketplace.com/peers/peer0.buyer.private.data.marketplace.com/:/etc/hyperledger/msp/peerBuyer
    #- ./crypto-config/peerOrganizations/seller.private.data.marketplace.com/peers/peer0.seller.private.data.marketplace.com/:/etc/hyperledger/msp/peerSeller
    #- ./crypto-config/peerOrganizations/observer.private.data.marketplace.com/peers/peer0.observer.private.data.marketplace.com/:/etc/hyperledger/msp/peerObserver
    #- ./crypto-config/peerOrganizations/buyer.private.data.marketplace.com/users/:/etc/hyperledger/msp/users
    #- ./crypto-config/peerOrganizations/seller.private.data.marketplace.com/users/:/etc/hyperledger/msp/users
    #- ./crypto-config/peerOrganizations/observer.private.data.marketplace.com/users/:/etc/hyperledger/msp/users
    - ./orderer.private.data.marketplace.com:/var/hyperledger/production/orderer
    ports:
    - 7050:7050

  peer.private.data.marketplace.com:
    container_name: peer.org.private.data.marketplace.com
    extends:
      file: peer-base.yaml
      service: peer-base
    volumes:
    - /var/run/:/host/var/run/
    #- ./peer.org.private.data.marketplace.com:/var/hyperledger/production
    - ./channel-artifacts/:/etc/hyperledger/configtx
    - ./channel-artifacts/:/opt/gopath/src/github.com/hyperledger/fabric/peer
    - ../contract:/opt/gopath/src/github.com/chaincode/privatedatamarketplace/node

  couchdb.organization.private.data.marketplace.com:
    container_name: couchdb.organization.private.data.marketplace.com
    image: hyperledger/fabric-couchdb:0.4.14
    environment:
    - COUCHDB_USER=
    - COUCHDB_PASSWORD=
