#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2.1'

volumes:
  orderer.private.data.marketplace.com:
  peer0.buyer.private.data.marketplace.com:
  peer1.buyer.private.data.marketplace.com:
  peer0.seller.private.data.marketplace.com:
  peer1.seller.private.data.marketplace.com:
  peer0.observer.private.data.marketplace.com:
  peer1.observer.private.data.marketplace.com:

services:
#  cli:
#    container_name: cli
#    image: hyperledger/fabric-tools
#    tty: true
#    environment:
#    - GOPATH=/opt/gopath
#    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#    - FABRIC_LOGGING_SPEC=info
#    - CORE_PEER_ID=cli
#    - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
#    - CORE_CHAINCODE_KEEPALIVE=10
#    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#    command: /bin/bash
#    volumes:
#    - /var/run/:/host/var/run/
#    - ./../chaincode/:/opt/gopath/src/github.com/
#    - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
#    - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/channel-artifacts/
#    - ../contract/:/opt/gopath/src/github.com/hyperledger/fabric/peer
#    networks:

  ca.buyer.private.data.marketplace.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.buyer.private.data.marketplace.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.buyer.private.data.marketplace.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    #command: sh -c 'fabric-ca-server start -b admin:adminpw'
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.buyer.private.data.marketplace.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/buyer.private.data.marketplace.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.buyer.private.data.marketplace.com
    networks:
      - privatedatamarketplace

  ca.seller.private.data.marketplace.com:
    image: hyperledger/fabric-ca
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca.seller.private.data.marketplace.com
    - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.seller.private.data.marketplace.com-cert.pem
    - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
    - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.seller.private.data.marketplace.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
    - ./crypto-config/peerOrganizations/seller.private.data.marketplace.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.seller.private.data.marketplace.com
    networks:
    - privatedatamarketplace

  ca.observer.private.data.marketplace.com:
    image: hyperledger/fabric-ca
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca.observer.private.data.marketplace.com
    - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.observer.private.data.marketplace.com-cert.pem
    - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
    ports:
    - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.observer.private.data.marketplace.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
    - ./crypto-config/peerOrganizations/observer.private.data.marketplace.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.observer.private.data.marketplace.com
    networks:
    - privatedatamarketplace

  orderer.private.data.marketplace.com:
    extends:
      file: docker-compose-base.yaml
      service: orderer.private.data.marketplace.com
    container_name: orderer.private.data.marketplace.com
    networks:
    - privatedatamarketplace

  peer0.buyer.private.data.marketplace.com:
    container_name: peer0.buyer.private.data.marketplace.com
    extends:
      file: docker-compose-base.yaml
      service: peer.private.data.marketplace.com
    environment:
    - CORE_PEER_ID=peer0.buyer.private.data.marketplace.com
    - CORE_PEER_ADDRESS=peer0.buyer.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.buyer.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.buyer.private.data.marketplace.com:7051
    - CORE_PEER_LOCALMSPID=BuyerMSP
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.buyer.private.data.marketplace.com:5984
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/buyer.private.data.marketplace.com/peers/peer0.buyer.private.data.marketplace.com/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/buyer.private.data.marketplace.com/peers/peer0.buyer.private.data.marketplace.com/tls:/etc/hyperledger/fabric/tls
    - ./crypto-config/peerOrganizations/buyer.private.data.marketplace.com/users:/etc/hyperledger/msp/users
    - peer0.buyer.private.data.marketplace.com:/var/hyperledger/production
    ports:
    - 7051:7051
    - 7053:7053
    networks:
      - privatedatamarketplace
    depends_on:
      - orderer.private.data.marketplace.com
      - couchdb0.buyer.private.data.marketplace.com

  couchdb0.buyer.private.data.marketplace.com:
    container_name: couchdb0.buyer.private.data.marketplace.com
    extends:
      file: docker-compose-base.yaml
      service: couchdb.organization.private.data.marketplace.com
    ports:
      - "7984:5984"
    networks:
      - privatedatamarketplace

  peer1.buyer.private.data.marketplace.com:
    container_name: peer1.buyer.private.data.marketplace.com
    extends:
      file: docker-compose-base.yaml
      service: peer.private.data.marketplace.com
    environment:
    - CORE_PEER_ID=peer1.buyer.private.data.marketplace.com
    - CORE_PEER_ADDRESS=peer1.buyer.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.buyer.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.buyer.private.data.marketplace.com:7051
    - CORE_PEER_LOCALMSPID=BuyerMSP
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.buyer.private.data.marketplace.com:5984
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/buyer.private.data.marketplace.com/peers/peer1.buyer.private.data.marketplace.com/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/buyer.private.data.marketplace.com/peers/peer1.buyer.private.data.marketplace.com/tls:/etc/hyperledger/fabric/tls
    - ./crypto-config/peerOrganizations/buyer.private.data.marketplace.com/users:/etc/hyperledger/msp/users
    - peer1.buyer.private.data.marketplace.com:/var/hyperledger/production
    ports:
    - 8051:7051
    - 8053:7053
    networks:
    - privatedatamarketplace
    depends_on:
      - orderer.private.data.marketplace.com
      - couchdb1.buyer.private.data.marketplace.com

  couchdb1.buyer.private.data.marketplace.com:
    container_name: couchdb1.buyer.private.data.marketplace.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "8984:5984"
    networks:
      - privatedatamarketplace

  peer0.seller.private.data.marketplace.com:
    container_name: peer0.seller.private.data.marketplace.com
    extends:
      file: docker-compose-base.yaml
      service: peer.private.data.marketplace.com
    environment:
    - CORE_PEER_ID=peer0.seller.private.data.marketplace.com
    - CORE_PEER_ADDRESS=peer0.seller.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.seller.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.seller.private.data.marketplace.com:7051
    - CORE_PEER_LOCALMSPID=SellerMSP
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.seller.private.data.marketplace.com:5984
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/seller.private.data.marketplace.com/peers/peer0.seller.private.data.marketplace.com/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/seller.private.data.marketplace.com/peers/peer0.seller.private.data.marketplace.com/tls:/etc/hyperledger/fabric/tls
    - ./crypto-config/peerOrganizations/seller.private.data.marketplace.com/users:/etc/hyperledger/msp/users
    - peer0.seller.private.data.marketplace.com:/var/hyperledger/production
    ports:
    - 9051:7051
    - 9053:7053
    networks:
    - privatedatamarketplace
    depends_on:
      - orderer.private.data.marketplace.com
      - couchdb0.seller.private.data.marketplace.com

  couchdb0.seller.private.data.marketplace.com:
    container_name: couchdb0.seller.private.data.marketplace.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "9984:5984"
    networks:
      - privatedatamarketplace

  peer1.seller.private.data.marketplace.com:
    container_name: peer1.seller.private.data.marketplace.com
    extends:
      file: docker-compose-base.yaml
      service: peer.private.data.marketplace.com
    environment:
    - CORE_PEER_ID=peer1.seller.private.data.marketplace.com
    - CORE_PEER_ADDRESS=peer1.seller.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.seller.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seller.private.data.marketplace.com:7051
    - CORE_PEER_LOCALMSPID=SellerMSP
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.seller.private.data.marketplace.com:5984
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/seller.private.data.marketplace.com/peers/peer1.seller.private.data.marketplace.com/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/seller.private.data.marketplace.com/peers/peer1.seller.private.data.marketplace.com/tls:/etc/hyperledger/fabric/tls
    - ./crypto-config/peerOrganizations/seller.private.data.marketplace.com/users:/etc/hyperledger/msp/users
    - peer1.seller.private.data.marketplace.com:/var/hyperledger/production
    ports:
    - 10051:7051
    - 10053:7053
    networks:
    - privatedatamarketplace
    depends_on:
      - orderer.private.data.marketplace.com
      - couchdb1.seller.private.data.marketplace.com

  couchdb1.seller.private.data.marketplace.com:
    container_name: couchdb1.seller.private.data.marketplace.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "10984:5984"
    networks:
      - privatedatamarketplace

  peer0.observer.private.data.marketplace.com:
    container_name: peer0.observer.private.data.marketplace.com
    extends:
      file: docker-compose-base.yaml
      service: peer.private.data.marketplace.com
    environment:
    - CORE_PEER_ID=peer0.observer.private.data.marketplace.com
    - CORE_PEER_ADDRESS=peer0.observer.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.observer.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.observer.private.data.marketplace.com:7051
    - CORE_PEER_LOCALMSPID=ObserverMSP
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.observer.private.data.marketplace.com:5984
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/observer.private.data.marketplace.com/peers/peer0.observer.private.data.marketplace.com/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/observer.private.data.marketplace.com/peers/peer0.observer.private.data.marketplace.com/tls:/etc/hyperledger/fabric/tls
    - ./crypto-config/peerOrganizations/observer.private.data.marketplace.com/users:/etc/hyperledger/msp/users
    - peer0.observer.private.data.marketplace.com:/var/hyperledger/production
    ports:
    - 11051:7051
    - 11053:7053
    networks:
    - privatedatamarketplace
    depends_on:
      - orderer.private.data.marketplace.com
      - couchdb0.observer.private.data.marketplace.com

  couchdb0.observer.private.data.marketplace.com:
    container_name: couchdb0.observer.private.data.marketplace.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "11984:5984"
    networks:
      - privatedatamarketplace

  peer1.observer.private.data.marketplace.com:
    container_name: peer1.observer.private.data.marketplace.com
    extends:
      file: docker-compose-base.yaml
      service: peer.private.data.marketplace.com
    environment:
    - CORE_PEER_ID=peer1.observer.private.data.marketplace.com
    - CORE_PEER_ADDRESS=peer1.observer.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.observer.private.data.marketplace.com:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.observer.private.data.marketplace.com:7051
    - CORE_PEER_LOCALMSPID=ObserverMSP
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.observer.private.data.marketplace.com:5984
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/observer.private.data.marketplace.com/peers/peer1.observer.private.data.marketplace.com/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/observer.private.data.marketplace.com/peers/peer1.observer.private.data.marketplace.com/tls:/etc/hyperledger/fabric/tls
    - ./crypto-config/peerOrganizations/observer.private.data.marketplace.com/users:/etc/hyperledger/msp/users
    - peer1.observer.private.data.marketplace.com:/var/hyperledger/production
    ports:
    - 12051:7051
    - 12053:7053
    networks:
    - privatedatamarketplace
    depends_on:
      - orderer.private.data.marketplace.com
      - couchdb1.observer.private.data.marketplace.com

  couchdb1.observer.private.data.marketplace.com:
    container_name: couchdb1.observer.private.data.marketplace.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "12984:5984"
    networks:
      - privatedatamarketplace

networks:
  privatedatamarketplace:
    external: true
    name: privatedatamarketplace
